import PDFDocument from "pdfkit";
import QRCode from "qrcode";

export const buildQrDataUrl = async (payload) =>
  QRCode.toDataURL(JSON.stringify(payload), { margin: 1, width: 280 });

export const buildBadgePdfBuffer = async ({ passCode, visitorName, hostName, visitDate, qrImage }) =>
  new Promise((resolve) => {
    const doc = new PDFDocument({ size: "A6", margin: 24 });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc.roundedRect(16, 16, 266, 384, 18).fillAndStroke("#f8fbff", "#d6deea");
    doc.fillColor("#20304c").fontSize(18).text("Visitor Pass", 32, 32, { align: "center" });
    doc.fillColor("#ff5a7d").fontSize(12).text(passCode, 32, 64, { align: "center" });

    doc.fillColor("#20304c").fontSize(11);
    doc.text(`Visitor: ${visitorName}`, 32, 108);
    doc.text(`Host: ${hostName}`, 32, 130);
    doc.text(`Visit Date: ${new Date(visitDate).toLocaleString()}`, 32, 152, { width: 150 });

    if (qrImage) {
      doc.image(qrImage, 165, 112, { width: 88, height: 88 });
    }

    doc.moveTo(32, 226).lineTo(250, 226).strokeColor("#d6deea").stroke();
    doc.fillColor("#50627f").fontSize(10).text("Please show this pass at the front desk during check-in.", 32, 240, {
      width: 220,
      align: "left"
    });

    doc.fillColor("#20304c").fontSize(9).text("Generated by Visitor Pass Management System", 32, 332, {
      align: "center",
      width: 218
    });
    doc.end();
  });
